[package]
name = "hello_world"
version = "0.0.0"
publish = false

[dependencies]
rocket = "0.4.11"
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.6", features = [ "runtime-tokio-rustls" ] }
